---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Course: Tools and Techniques for Data Science</h1>

---
<h3><div align="right">Instructor: Muhammad Arif Butt, Ph.D.</div></h3>    

<h1 align="center">Lecture 3.1 (NumPy-01)</h1>

# _01-NumPy-ArrayCreation.ipynb_

<img align="center" width="400" height="400"  src="images/numpyintro.png" > 

# Learning agenda of this notebook
1. Introduction to Numpy Library
2. Array Creation using `np.array()` constructor
3. Miscellaneous Array Creation Functions
    - `np.zeros()`
    - `np.ones()`
    - `np.empty()`
    - `np.full()`
    - `np.eye()`
    - `np.fromstring()`
    - `np.arange()`
    - `np.linspace()`
    - `np.random.rand()`
    - `np.random.randint()`
    - `np.zeros_like()`

## 1. Introduction to Numpy Library
<img align="right" width="500" height="300"  src="images/ndarrays.png" > 

- *A **NumPy array** (https://numpy.org) is a numerically ordered sequence of elements stored contiguously in memory, that can store elements of homogeneous types (usually numbers but can be boolians, strings, or other objects), is iterable, mutable, non-growable/shrinkable and allows duplicate elements.*
- Some attributes of NumPy Array:
>- **ndim:** The number of dimensions, can be 1, 2, 3, ... N
>- **axis:** Each dimension is called an axis: `axis 0` is the vertical axis, goes from top to bottom, represents the number of rows, `axis 1` is the horizontal axis, goes from left to right, represents the number of columns, `axis 2` is the number of columns along z axis
>- **rank:** The number of axes is called the rank.
>- **shape:** It is a tuple whose length is the rank and elements are dimension of each axis.
>- **size:** It is the total number of elements, which is the product of all axis lengths.
>- **itemsize:** It gives you the size in bytes of each element of the array (depends on dtype).
>- **nbytes:** It gives you the total number of bytes occupied by entire array object in memory (size x itemsize).

In [4]:
# Unlike the other modules, we have been working so far, you have to download and install numPy
# To install this library in Jupyter notebook
import sys
!{sys.executable} -m pip install numpy

In [9]:
import numpy as np
np.__version__ , np.__path__

('1.19.5',
 ['/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy'])

## 2.  Array Creation using `np.array()` Constructor
```
np.array(seq, dtype)
```
- The only required argument is a sequence like object like a list from which to create an array
- The optional dtype argument specifies the data type of the array objects. For integer values it is normally int64, and for float objects it is float64.  You can pass dtype as an optional argument, if you want to limit memory usage. To check for available data types in Numpy check the value of **`np.sctypes`** attribute:
    - **`int`:** `numpy.int8, numpy.int16, numpy.int32, numpy.int64`
    - **`uint`:** `numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64`
    - **`float`:** `numpy.float16, numpy.float32, numpy.float64, numpy.float128`
    - **`complex`:** `numpy.complex64, numpy.complex128, numpy.complex256`
    - **`others`:** `bool, object, bytes, str, numpy.void`

In [3]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

### a.  Creating an Empty NumPy Array

In [4]:
import numpy as np
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


### b.  0-Dimensional Array
- A 0-D array has a single scalar value, and has zero or no axis

In [1]:
# Create a 0-D numpy array using array() constructor
import numpy as np
arr = np.array(10)
print("array: ", arr)

array:  10


### c.  1-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/1d.png" > 

- An array that has 0-D arrays or scalar values, as its elements is called a 1-D array. 
- Used to represent vectors or 1st order tensors.
- A 1-D array has only one axis:
    - **axis 0:** or vertical axis   or x-axis or number of rows

In [6]:
# Create a 1-D numpy array using array() constructor of numpy

mylist = [1, 4, 2, 5, 3]
arr = np.array(mylist, dtype=np.uint16)
arr = np.array([1, 4, 2, 5, 3], dtype=np.uint16)

print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions
print("arr.shape: ", arr.shape) # This is 1-D array having 5 columns, so return a tuple with one element
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (2*5=10)

array:  [1 4 2 5 3]
arr.ndim:  1
arr.shape:  (5,)
arr.size:  5
arr.dtype:  uint16
arr.itemsize:  2
arr.nbytes:  10


### d.  2-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/2d.png" > 

- An array that has 1-D arrays as its elements is called a 2-D array. 
- Used to represent matrix or 2nd order tensors.
- A 2-D array has two axis:
    - **axis 0:** is the vertical axis, goes from top to bottom, represents the number of rows (5)
    - **axis 1:** is the horizontal axis, goes from left to right, represents the number of columns (4)
- If you've taken a linear algebra class in high school, you may recognize this 2-d array as a matrix with five rows and four columns. 
- Each row represents a city, and the columns may contain temperature, rainfall, humidity, and smog in that city respectively.

In [7]:
# creating 2-D (5x4) array using array constructor in numpy

mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   #get number of dimensions (2-D array)
print("arr.shape: ", arr.shape) #get dimension size.For a 2-D array, return a tuple with two elements (rows, cols)
print("arr.size: ", arr.size)   #get total number of elements (5*4=20 elements)
print("arr.dtype: ", arr.dtype) #get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*20=160)

array:  [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]
arr.ndim:  2
arr.shape:  (5, 4)
arr.size:  20
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  160


### e.  3-Dimensional Arrays
<img align="left" width="200" height="100"  src="images/3d.png" > 

- An array that has 2-D arrays as its elements is called a 3-D array. Used to represent 3rd order tensors.
- A 3-D array has three axis:
    - **axis 0:** represent the number of rows along x-axis(axis 0). (5)
    - **axis 1:** represents the number of rows along y-axis (axis 1). (4)
    - **axis 2:** represents the number of columns along z-axis (axix 2). (3)

In [8]:
# creating 3-D (5x4x3) array using array constructor in numpy
mylist = [
          [[1, 2, 3], [5, 6, 7], [3, 2, 4], [7, 3, 4]],
          [[8, 1, 6], [1, 9, 4], [5, 6, 4], [2, 6, 2]],
          [[5, 3, 2], [2, 0, 5], [8, 3, 0], [5, 6, 9]],
          [[6, 7, 1], [8, 1, 6], [1, 4, 7], [2, 0, 4]],
          [[2, 8, 9], [3, 0, 4], [5, 2, 2], [1, 3, 8]],
         ]
arr = np.array(mylist)


print("array: ", arr)
print("arr.ndim: ", arr.ndim)    # get number of dimensions (3-D array)
print("arr.shape: ", arr.shape)  # get dimension size.For a 3-D array, return a tuple with three elements
print("arr.size: ", arr.size)    # get total number of elements (5*4*3=60 elements)
print("arr.dtype: ", arr.dtype)  # get data type, default is what is minimum required to hold the max size element
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory (8*60=4800)

array:  [[[1 2 3]
  [5 6 7]
  [3 2 4]
  [7 3 4]]

 [[8 1 6]
  [1 9 4]
  [5 6 4]
  [2 6 2]]

 [[5 3 2]
  [2 0 5]
  [8 3 0]
  [5 6 9]]

 [[6 7 1]
  [8 1 6]
  [1 4 7]
  [2 0 4]]

 [[2 8 9]
  [3 0 4]
  [5 2 2]
  [1 3 8]]]
arr.ndim:  3
arr.shape:  (5, 4, 3)
arr.size:  60
arr.dtype:  int64
arr.itemsize:  8
arr.nbytes:  480


## 3. Miscellaneous Array Creation Function
- Numpy also provides some handy methods to create arrays of desired shapes with fixed or random values. Check out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more.

<img align="right" width="150" height="100"  src="images/zeros.png"  > 

### a. Using `np.zeros()` Method
This method returns an array of given shape and type, filled with zeros.

```
numpy.zeros(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [9]:
# Creating 1-Dimensional array of all zeros
arr = np.zeros(3)
arr
# Notice that the elements are having the default data type as the float. That’s why the zeros are 0.

array([0., 0., 0.])

In [10]:
# Creating 2-Dimensional array filled with zeros
arr = np.zeros((2,3))
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Creating 2-Dimensional array filled with zeros of integer types
arr = np.zeros((2,3), dtype=np.int16)
arr, arr.nbytes

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 12)

<img align="right" width="100" height="100"  src="images/ones.png"  > 

### b. Using `np.ones()` Method
This method returns an array of given shape and type, filled with ones.

```
numpy.ones(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.

In [12]:
# Creating one-dimensional array with ones
arr = np.ones(3)
arr


array([1., 1., 1.])

In [13]:
# Creating 2-Dimensional array having 3 columns filled with ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Creating 2-Dimensional array having 3 columns filled with ones of integer types
arr = np.ones((2,3), dtype=np.int16)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

<img align="right" width="250" height="100"  src="images/empty.png"  > 

### c. Using `np.empty()` Method
This method returns an array of given shape and type, filled with junk values.

```
numpy.empty(shape, dtype=float)
```

- shape : The shape is an int or tuple of ints to define the size/shape of the array.
- dtype : The dtype is an optional parameter with default value as float.


Un-like numpy.zeros(), and numpy.ones(), the numpy.empty() function doesn't initialize the entries, so they contain junk values.

In [15]:
arr = np.empty(3)
arr

array([1., 1., 1.])

In [16]:
arr = np.empty(3, dtype=np.int16)
arr

array([257, 257, 257], dtype=int16)

In [23]:
# Creating 2-Dimensional array having 3 columns filled with junk values
arr = np.empty((2,3), dtype=np.int16)
arr

array([[     0,      0,      0],
       [     0, -25412, -11145]], dtype=int16)

<img align="right" width="200" height="100"  src="images/full.png"  > 

### d. Using `np.full()` Method
This method return a new array of given shape and type, filled with fill_value.
```
np.full(shape, fill_value, dtype=None)
```
- shape: Shape of the new array
- fill_value: Fill value.
- dtype	The desired data-type for the array

In [24]:
arr = np.full(7, 54)
arr

array([54, 54, 54, 54, 54, 54, 54])

In [25]:
arr = np.full(7, 21.5)
arr

array([21.5, 21.5, 21.5, 21.5, 21.5, 21.5, 21.5])

In [26]:
arr = np.full((2,3), 21.5)
arr

array([[21.5, 21.5, 21.5],
       [21.5, 21.5, 21.5]])

<img align="right" width="120" height="130"  src="images/eye.png"  >

### e. Using `np.eye()` Method
This method is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

```
eye(N, M=None, k=0 , dtype=float)
```
- N: Number of rows in the output
- M: Number of columns in the output. If None, defaults to N
- k: Index of the diagonal: (Default 0) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal
- dtype: Data-type of the returned array

In [28]:
# creating 2-D array using eye function
# with 2 rows and 2 columns having 1's at on the main diagonal
eye_arr = np.eye(3,3)
eye_arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at on the main diagonal
eye_arr = np.eye(4, 3, dtype=np.int8)
eye_arr


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int8)

In [30]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4, 3, k = 1, dtype=int)
eye_arr

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place lower
eye_arr = np.eye(4, 3, k = -1, dtype=int)
eye_arr

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<img align="right" width="200" height="150"  src="images/fromstring.png"  > 

### f. Using `np.fromstring()` Method
This function is used to create a new 1-D array initialized from raw binary or text data in a string.
```
np.fromstring(string, dtype, sep)
```
- string: A string containing the data
- dtype: The data type of the array (by default float)
- sep: The string separating numbers in the data

In [32]:
# convert the space separated string '25 30 35 40' into an floats array
arr = np.fromstring('25 30 35 40', sep=' ')
arr

array([25., 30., 35., 40.])

In [33]:
# convert the space separated string '25 30 35 40' into an integer array
arr = np.fromstring('25 30 35 40', sep=' ', dtype=np.uint8)
arr

array([25, 30, 35, 40], dtype=uint8)

In [34]:
# converting comma separated string into float type array
arr = np.fromstring('0.7, 10.4, 50.5', sep=",")
print(arr)


[ 0.7 10.4 50.5]


In [35]:
# It will raise error
arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')

/var/folders/1t/g3ylw8h50cjdqmk5d6jh1qmm0000gn/T/ipykernel_30410/1942666505.py:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  arr = np.fromstring('0.57, str, 50.555', dtype=float, sep=',')


### g. Using `np.arange()` Method
<img align="right" width="200" height="100"  src="images/arrange.png"  > 
This function is used to get evenly spaced values within a given interval.

```
numpy.arange([start,] stop[, step])
```
- If only one argument is given will generate an int64 array from zero to that value (not inclusive)
- If two arguments are given then start value in inclusive, stop value is not inclusive and the default step is 1
- If three arguments are given then the third argument is the distance between two adjacent values. (default step size is 1)
- All the three arguments can be integers or floats

The image shows the array created by np.arange(5,9,1)


In [36]:
arr = np.arange(5)
print(arr)
print(arr.dtype)

[0 1 2 3 4]
int64


In [37]:
arr = np.arange(5, dtype=float)
print(arr)
print(arr.dtype)

[0. 1. 2. 3. 4.]
float64


In [38]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [39]:
arr = np.arange(5, 10, 2)
arr

array([5, 7, 9])

In [40]:
arr = np.arange(10, 5, -1)
arr

array([10,  9,  8,  7,  6])

In [41]:
arr = np.arange(-1, -4, -.5)
arr

array([-1. , -1.5, -2. , -2.5, -3. , -3.5])

In [42]:
arr = np.arange(1, 5, .5)
print(arr)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### h. Using `np.linspace()` Method
<img align="right" width="300" height="200"  src="images/linspace1.png"  > 

This method by default returns an array of 50 evenly spaced elements starting from the first argument (inclusive) to the second argument (inclusive). The third argument, if given, is the count of number of elements of the array, default is 50.

```
numpy.linspace(start, stop, num=50)
```

In [43]:
arr = np.linspace(2,3,4)
print(arr)
print(arr.dtype)

[2.         2.33333333 2.66666667 3.        ]
float64


In [45]:
arr = np.linspace(1,2)
print(arr)
print(arr.dtype)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]
float64


In [46]:
arr = np.linspace(-1,-5)
print(arr)

[-1.         -1.08163265 -1.16326531 -1.24489796 -1.32653061 -1.40816327
 -1.48979592 -1.57142857 -1.65306122 -1.73469388 -1.81632653 -1.89795918
 -1.97959184 -2.06122449 -2.14285714 -2.2244898  -2.30612245 -2.3877551
 -2.46938776 -2.55102041 -2.63265306 -2.71428571 -2.79591837 -2.87755102
 -2.95918367 -3.04081633 -3.12244898 -3.20408163 -3.28571429 -3.36734694
 -3.44897959 -3.53061224 -3.6122449  -3.69387755 -3.7755102  -3.85714286
 -3.93877551 -4.02040816 -4.10204082 -4.18367347 -4.26530612 -4.34693878
 -4.42857143 -4.51020408 -4.59183673 -4.67346939 -4.75510204 -4.83673469
 -4.91836735 -5.        ]


### i. Using `np.random.rand()` Method
- This method generates an array of random floats (between 0 and 1) of as many dimensions passed as argument.
- If no argument is passed, generates a scalar value between 0 and 1

```
numpy.random.rand(d0 [,d1] [,d2]....)
```


In [57]:
#Python's built-in random module has random() function that returns a single float between 0 and 1
import random
value = random.random()
value

0.2516260164179611

In [58]:
# Creating 1-D array of 5 elements of random floats between 0 and 1
arr = np.random.rand(5)
arr


array([0.73330424, 0.43812661, 0.56596848, 0.45486744, 0.51214531])

In [64]:
# Creating 1-D array of 5 elements of random floats between 0 and 10
arr = np.random.rand(5)*10
arr


array([4.33607362, 0.78119092, 4.10859073, 1.37162561, 1.70376317])

In [65]:
# Creating 2-D array (4x3) having random floats between 0 and 1
arr = np.random.rand(4,3)
arr

array([[0.26865913, 0.79707145, 0.73026312],
       [0.04682302, 0.48705421, 0.17333337],
       [0.86869311, 0.95222452, 0.84177373],
       [0.27084945, 0.50562113, 0.99702055]])

In [66]:
# Creating 2-D array (4x3) having random floats between 0 and 10
arr = np.random.rand(4,3)*10
arr

array([[6.22757893, 5.51504268, 7.37091015],
       [4.71260541, 1.59607495, 6.56987965],
       [8.03573863, 9.11115861, 0.43321932],
       [1.57134618, 5.07485563, 8.36027025]])

In [67]:
# Creating 3-D array of with random values using np.random.rand()
arr = np.random.rand(5,4,3)
arr

array([[[0.46022229, 0.68568631, 0.02691946],
        [0.32932096, 0.31757644, 0.58400298],
        [0.8748877 , 0.62493768, 0.33046376],
        [0.47144154, 0.95754875, 0.6939116 ]],

       [[0.72138725, 0.37898658, 0.71886202],
        [0.35410542, 0.10208396, 0.43341983],
        [0.63056472, 0.25882903, 0.89294499],
        [0.8045415 , 0.36717918, 0.917939  ]],

       [[0.35047891, 0.34515628, 0.45087798],
        [0.3941456 , 0.62580203, 0.78587664],
        [0.28688956, 0.53597233, 0.64760892],
        [0.16349175, 0.35212498, 0.59345578]],

       [[0.94353131, 0.96802591, 0.87076817],
        [0.62120313, 0.37112594, 0.39225916],
        [0.06170176, 0.42090752, 0.1468633 ],
        [0.59785886, 0.02603709, 0.11847262]],

       [[0.85308663, 0.50297553, 0.40250721],
        [0.30585556, 0.42862618, 0.5787846 ],
        [0.19915658, 0.97327125, 0.7416632 ],
        [0.29412694, 0.97579625, 0.85737534]]])

### i. Using `np.random.randint()` Method
This method returns an array of specified shape and fills it with random integers.
```
numpy.random.randint(low, high=None, size)
```
- low: Lowest (signed) integer to be drawn from the distribution. But, it works as a highest integer in the sample if high=None.
- high: Largest (signed) integer to be drawn from the distribution (not inclusive)
- size: number of samples to be generated (default is 1 for scalar and >1 for 1-D array and a tupple for ndarray)

In [68]:
# Generating a random integer scalar b/w interval (0,9) 
value = np.random.randint(10)
value

2

In [71]:
# Generating a random integer scalar b/w interval (5,19) 
value = np.random.randint(low=5, high=20)
value

13

In [81]:
# Generating a random integer scalar from -5 to 4 
value = np.random.randint(low=-5, high=5)
value

3

In [86]:
# creating 1-D array of size 6 of int type b/w interval (1,100) 
arr = np.random.randint(low=1, high=101, size=6)
arr

array([11, 99, 52, 35, 80, 40])

In [87]:
# creating 1-D array of size 6 of int type b/w interval (-5,4) 
arr = np.random.randint(low = -5, high = 5, size = 4)
arr

array([-2, -1, -3, -1])

In [101]:
# By passing a tuple to size means rows and columns
arr = np.random.randint(low = 1, high = 10, size = (3,3))
arr

array([[8, 5, 8],
       [4, 2, 6],
       [3, 4, 4]])

In [102]:
arr = np.random.randint(low = 1, high = 10, size = (2,3,4))
arr

array([[[1, 3, 1, 9],
        [7, 3, 8, 2],
        [9, 2, 9, 6]],

       [[7, 3, 5, 6],
        [5, 1, 1, 2],
        [6, 1, 7, 3]]])

<img align="right" width="100" height="130"  src="images/zeros_like.png"  >

### k. Using `np.zeros_like()` Method
This method is used to get an array of zeros with the same shape and type as a given array.

```
zeros_like(arr, dtype=None) 
```

- arr: array like input
- dtype: Overrides the data type of the result

In [103]:
# creating a 2-D array
mylist = [[0, 1],[2, 3]]
arr1 = np.array(mylist)
print("A 2-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)


A 2-D array 
 [[0 1]
 [2 3]]

 Converted Array 
 [[0 0]
 [0 0]]


In [104]:
# creating 1-D array
arr1 = np.arange(10)
print("A 1-D array \n", arr1)

# creating the same array as the shape of 'arr' filled with zeros
arr2 = np.zeros_like(arr1)
print("\n Converted Array \n", arr2)


A 1-D array 
 [0 1 2 3 4 5 6 7 8 9]

 Converted Array 
 [0 0 0 0 0 0 0 0 0 0]
